# Requires a valid GITHUB_TOKEN
# --build-arg GITHUB_TOKEN=xxxx

# Runs goreleaser in Boring Crypto Go container in order to allow
# goreleaser to build a valid Boring Crypto binary

FROM goboring/golang:1.15.6b5

ARG GITHUB_TOKEN
ARG VERSION

# goreleaser v1.2.0 checksum fails. See https://github.com/goreleaser/godownloader/issues/207 
RUN curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh -s -- v1.1.0

WORKDIR /app
ADD . .

RUN go mod download
RUN GITHUB_TOKEN=$GITHUB_TOKEN GORELEASER_CURRENT_TAG=$VERSION goreleaser release --rm-dist --skip-validate
