---
debug: true
server:
  listen-addr: ":8080"
  read-timeout: "1s"
  magic: 1097911063
  # magic: 764824073
  max-peers: 10  # max entries to return in http queries.
  default-peer: "relays-new.cardano-testnet.iohkdev.io:3001"
  # default-peer: "relays-new.cardano-mainnet.iohk.io:3001"
client:
  ### how often to connect to ogmios websocket and fetch pool parameters.
  enabled: true
  period-seconds: "3600s"  # controls how often the process will be repeated.
  fetch-max: 8000  # size of the go channel reading pool parameters at each iteration.
  endpoint: "ws://localhost:8337"
  probe-timeout: "1s"  # tcp probe timeout, a pool relay will be discarded if it does not answer (host down) to the tcp probe.
